import{a as w,S as M,i as c}from"./assets/vendor-03da8548.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const v="42985192-59b08832658772ec4fe41b848",C="https://pixabay.com/api/";async function p(t,e,s){try{return(await w.get(C,{params:{key:v,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:s}})).data}catch(n){throw console.error("Error fetching images:",n),n}}const a=document.querySelector(".gallery"),g=new M(".gallery a",{captionsData:"alt",captionDelay:250});g.refresh();function y(t){t.forEach(e=>{const s=`
      <li class="card">
        <a href="${e.largeImageURL}" class="link">
          <img src="${e.webformatURL}" alt="${e.tags}">
          <ul class="list-container">
          <li class="item-description"><h3>Likes</h3> <p>${e.likes}</p></li>
          <li class="item-description"><h3>Views</h3> <p>${e.views}</p></li>
          <li class="item-description"><h3>Comments</h3> <p>${e.comments}</p></li>
          <li class="item-description"><h3>Downloads</h3> <p>${e.downloads}</p></li>
        </ul>
        </a>
        
      </li>
    `;a.insertAdjacentHTML("beforeend",s)}),g.refresh()}function L(){const t=document.createElement("p");t.classList.add("end-message"),t.textContent="Sorry, but thats it)",a.insertAdjacentElement("afterend",t)}const S=document.querySelector(".form"),h=document.querySelector(".search-input"),E=document.querySelector(".loader");m();let l="",i=1;const f=15;S.addEventListener("submit",H);async function H(t){if(t.preventDefault(),l=h.value.trim(),i=1,a.innerHTML="",l===""){c.error({title:"Error",message:"Please enter a search term.",position:"topCenter"}),d();return}q(),b();try{const e=await p(l,i,f),s=e.totalHits;if(e.hits.length===0){a.innerHTML="",c.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"}),d();return}else y(e.hits),h.value="",P();f*i>=s&&(d(),L())}catch(e){console.error("Error fetching images:",e),c.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topCenter"})}finally{m()}}loadMoreBtn.addEventListener("click",async()=>{try{loadMoreBtn&&(i+=1);const t=await p(l,i,f),e=t.totalHits;y(t.hits),b(),f*i>=e&&(d(),L());const s=a.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:s*3,behavior:"smooth"})}catch(t){console.error("Error fetching more images:",t),c.error({title:"Error",message:`Error fetching more images: ${t}`})}finally{m()}});function b(){E.classList.remove("hidden")}function m(){E.classList.add("hidden")}function P(){loadMoreBtn.style.display="block"}function d(){loadMoreBtn.style.display="none"}function q(){const t=document.querySelector(".end-message");t&&t.remove()}
//# sourceMappingURL=commonHelpers.js.map
